name: "Allocation"
on:
  push:
    paths:
      - '/src/garuda/allocation/**'
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main ]
  release:
    types: [ published ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  setup-build:
    name: setup-build
    strategy:
      matrix:
        version : [17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: '/src/garuda/allocation/'
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.version }}
          cache: gradle
      - name: "Build the configured project"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan -x test

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test